language: python
sudo: required
dist: xenial
group: travis_latest
python:
- 3.7
- 3.6
- 3.5
- 2.7

git:
  depth: 3
  quiet: true

install: pip install .[tests]

script: 
  - pytest -v -s gtts/tests/ --cov-report= --cov=gtts
  - flake8

after_success: coveralls

deploy:
  provider: pypi
  user: pndurette
  password:
    secure: GTbUTja0D/LDnIxLLO4ohTHGugwrnx2nMqAw5n7a9JAsfxCVXz6+vu0fkNBmOSJV0bNsFcoj/Q+lcR1SCNsw2NibWWFLDMoYD/yqP/SrHTSUoTXt+o7H9/qvxR2MDr0t2S5kjAux4bw5uPg8WtYlPpD0VWgWkFCm3JmJG+cG1tA=
  on:
    tags: true
    distributions: sdist
    repo: pndurette/gTTS
    branch: master
    python: '3.6'
